### PR TITLE
Fix `epic_key` column in list call. Closes #75

### LINKED ISSUE #75: Strange result sets using epic_key in jira_issue table
**Describe the bug**
When querying key and epic_key using project_key column key the epic_key returns NULL.  

```sql
select key, 
epic_key, 
project_key 
from jira_issue 
where project_key = 'BDT' LIMIT 10;
```
Result set

```
+----------+----------+-------------+
| key      | epic_key | project_key |
+----------+----------+-------------+
| BDT-4357 | <null>   | BDT         |
| BDT-4360 | <null>   | BDT         |
| BDT-4361 | <null>   | BDT         |
| BDT-4362 | <null>   | BDT         |
| BDT-4364 | <null>   | BDT         |
| BDT-4365 | <null>   | BDT         |
| BDT-4363 | <null>   | BDT         |
| BDT-4366 | <null>   | BDT         |
| BDT-4358 | <null>   | BDT         |
| BDT-4359 | <null>   | BDT         |
+----------+----------+-------------+
```

When querying key and epic_key using specific keys (as returned above) the epic_key is returned.

```sql
select key,
epic_key,
project_key
from jira_issue 
where key in ('BDT-4366',
'BDT-4357',
'BDT-4365',
'BDT-4363',
'BDT-4364',
'BDT-4360',
'BDT-4361',
'BDT-4359',
'BDT-4362',
'BDT-4358');
```
Result set
```
+----------+----------+-------------+
| key      | epic_key | project_key |
+----------+----------+-------------+
| BDT-4358 | BDT-2717 | BDT         |
| BDT-4365 | BDT-4364 | BDT         |
| BDT-4366 | BDT-4364 | BDT         |
| BDT-4364 | <null>   | BDT         |
| BDT-4363 | BDT-4362 | BDT         |
| BDT-4359 | BDT-4177 | BDT         |
| BDT-4357 | BDT-4177 | BDT         |
| BDT-4361 | BDT-4177 | BDT         |
| BDT-4360 | BDT-3654 | BDT         |
| BDT-4362 | <null>   | BDT         |
+----------+----------+-------------+
```

When query again later (in cli or from command line), the results are what they are expected to be for the first query.

```
+----------+----------+-------------+
| key      | epic_key | project_key |
+----------+----------+-------------+
| BDT-4357 | BDT-4177 | BDT         |
| BDT-4360 | BDT-3654 | BDT         |
| BDT-4361 | BDT-4177 | BDT         |
| BDT-4362 | <null>   | BDT         |
| BDT-4364 | <null>   | BDT         |
| BDT-4365 | BDT-4364 | BDT         |
| BDT-4363 | BDT-4362 | BDT         |
| BDT-4366 | BDT-4364 | BDT         |
| BDT-4358 | BDT-2717 | BDT         |
| BDT-4359 | BDT-4177 | BDT         |
+----------+----------+-------------+
```

**Steampipe version (`steampipe -v`)**

```
❯ steampipe -v
Steampipe v0.18.6
```

**Plugin version (`steampipe plugin list`)**

```
❯ steampipe plugin list
+----------------------------------------------------+---------+-------------+
| Installed Plugin                                   | Version | Connections |
+----------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/theapsgroup/gitlab@latest | 0.2.2   | gitlab      |
| hub.steampipe.io/plugins/turbot/aws@latest         | 0.94.0  | aws         |
| hub.steampipe.io/plugins/turbot/jira@latest        | 0.8.0   | jira        |
| hub.steampipe.io/plugins/turbot/steampipe@latest   | 0.6.0   | steampipe   |
+----------------------------------------------------+---------+-------------+
```

**To reproduce**
See above.

**Expected behavior**
The first query should not return null.

### PR DESCRIPTION
**Pull request by karanpopat**
# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  key,
  id, 
  epic_key,
  project_key
from
  jira_issue
where
  key in ('SBT-1', 'SBT-2', 'SBT-3')
+-------+-------+----------+-------------+
| key   | id    | epic_key | project_key |
+-------+-------+----------+-------------+
| SBT-3 | 10052 | SBT-1    | SBT         |
| SBT-1 | 10050 | <null>   | SBT         |
| SBT-2 | 10051 | SBT-1    | SBT         |
+-------+-------+----------+-------------+

Time: 396ms. Rows fetched: 1. Hydrate calls: 0.
> select
  key,
  id,
  epic_key,
  project_key
from
  jira_issue
where
  project_key = 'SBT'
+-------+-------+----------+-------------+
| key   | id    | epic_key | project_key |
+-------+-------+----------+-------------+
| SBT-3 | 10052 | SBT-1    | SBT         |
| SBT-1 | 10050 | <null>   | SBT         |
| SBT-2 | 10051 | SBT-1    | SBT         |
+-------+-------+----------+-------------+

Time: 0.9s. Rows fetched: 3. Hydrate calls: 3.
```
</details>

### CODE REVIEW

File: jira/table_jira_issue.go [hunk 1]
```diff
@@ -307,12 +308,19 @@ func listIssues(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData)
...
-	issueId := d.EqualsQuals["id"].GetStringValue()
-	key := d.EqualsQuals["key"].GetStringValue()
+	var issueId, key string
+	if h.Item != nil {
+		issueInfo := h.Item.(IssueInfo)
+		issueId = issueInfo.ID
+		key = issueInfo.Key
+	} else {
+		issueId = d.EqualsQuals["id"].GetStringValue()
+		key = d.EqualsQuals["key"].GetStringValue()
```
Comment (misraved) [inline jira/table_jira_issue.go:322]:
```suggestion
		issueId = d.EqualsQualString["id"]
		key = d.EqualsQualString["key"]
```

**Review by misraved — COMMENTED** [review]
@karanpopat thanks for looking into this issue 👍. I have left a minor review comment.

Also, do the APIs for `ListConfig` and `GetConfig` return similar data for the `epic_key` column?

Could you please add different example queries in the PR body to justify that both APIs return similar values?

**Comment by karanpopat** [comment]
@misraved 
Findings:

- The SDK is not returning the custom fields in the List call - `epic_key` is a part of the custom fields. Have raised an issue for the same  - https://github.com/andygrunwald/go-jira/issues/636
- The issue persists even after updating the SDK
- One workaround could be by using the get api as hydrate for the column. Which is of course an extra api call.
- Another would be to use the raw [searchIssue](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-search/#api-rest-api-3-search-get) endpoint to fetch the List call data, which returns some means to fetch the epic data. 

Have modified the list call in this PR to use the `rest/api/2/search` endpoint.

**Review by misraved — APPROVED** [review]
